# Generated by Django 3.2.5 on 2021-11-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='boston',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='dc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expenses',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='expense',
            name='philly',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='roanoke',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='seattle',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='sf',
            field=models.FloatField(),
        ),
    ]
